apiVersion: batch/v1
kind: Job
metadata:
  name: single-execution
spec:
  template:
    spec:
      containers:
        - command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Job starting ..."
              sleep 10
              echo "... job done"
          image: busybox
          name: single
      restartPolicy: Never
