apiVersion: batch/v1
kind: Job
metadata:
  name: update-attempt
spec:
  template:
    spec:
      containers:
        - command: ["/bin/sh"]
          args:
            - -c
            - |
              echo $(START_MESSAGE)
              for i in `seq 1 10`
              do
                  echo "$ITEM_MESSAGE $i"
              done
              echo $END_MESSAGE
          image: busybox
          name: single
          env:
            - name: START_MESSAGE
              value: Job starting ...
            - name: END_MESSAGE
              value: ... job done
            - name: ITEM_MESSAGE
              value: Processing item number
      restartPolicy: Never
